language: elixir
otp_release:
  - 22.0
elixir:
  - 1.6.6
  - 1.7.4
  - 1.8.2
  - 1.9.0
matrix:
  include:
    - elixir: 1.6.6
      otp_release: 21.3
  exclude:
    - elixir: 1.6.6
      otp_release: 22.0
dist: trusty
script:
  - mix dialyzer --halt-exit-status
  - mix coveralls.travis --include property_based
before_script:
  - MIX_ENV=test mix compile --warnings-as-errors
  - travis_wait mix dialyzer --plt
cache:
  directories:
    - _build
    - deps
